[tool.isort]
profile = "black"

[tool.black]
line-length = 100
target-version = ['py311']

[tool.flake8]
max-line-length = 125
extend-ignore = ["E203", "W503", "F841"]
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "dist",
    "*.egg-info"
]
