groups:
  - name: terraform-agent-alerts
    rules:
      - alert: HighEstimatedCosts
        expr: terraform_agent_estimated_costs_usd > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High estimated monthly cost"
          description: "Estimated monthly costs exceed $1000 for over 5 minutes."

      - alert: HighErrorRate
        expr: increase(terraform_agent_errors_total[5m]) / 300 > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate"
          description: "Error rate exceeded 0.1 errors/second over the last 5 minutes."
