name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./src

    - name: Install linting and testing tools
      run: pip install black isort flake8 flake8-pyproject mypy pytest

    - name: Run black formatter check
      run: black --check --line-length 100 .
      working-directory: ./src

    - name: Run isort import check
      run: isort --check-only .
      working-directory: ./src

    - name: Run flake8 linter
      run: flake8 . --config=../pyproject.toml
      working-directory: ./src

    - name: Run mypy static type checker
      run: mypy --ignore-missing-imports .
      working-directory: ./src

    - name: Run pytest
      run: pytest -q
      working-directory: ./src
